services:
  - type: static
    name: wedding-invitation
    repo: https://github.com/lceballosa/wedding_invitation
    branch: main
    autoDeploy: true
    buildCommand: >-
      if [ ! -d "flutter" ]; then
        git clone https://github.com/flutter/flutter.git -b stable flutter;
      fi &&
      export PATH="$PATH:$(pwd)/flutter/bin" &&
      flutter config --enable-web &&
      flutter pub get &&
      flutter build web --no-tree-shake-icons --no-wasm-dry-run
    staticPublishPath: ./build/web
    routes:
      - path: /*
        destination: /index.html

